### ISSUE TITLE
Jenkins support

### ISSUE THREAD

**Issue by mycargus** [flexport/quarantine#14]
Hullo! I love this project. I'd like to add Jenkins support. I'd like to take a stab at it and submit a pull request if that's alright. Anything you'd like to discuss before I do?

**Comment by alekstorm** [comment]
You can now integrate with any CI using [the `extra_attributes` setting](https://github.com/flexport/quarantine/tree/9ce8bf43664a7a422b044477dc7d36cf74e63638#setup-jira-workflow).
